#!/usr/bin/env python3
"""Export shared parser constants from Python to a JS module for web usage."""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    from media_filename_parser.rules import constants as c
except ModuleNotFoundError:
    REPO_ROOT = Path(__file__).resolve().parents[1]
    SRC_DIR = REPO_ROOT / "src"
    if SRC_DIR.exists():
        sys.path.insert(0, str(SRC_DIR))
    from media_filename_parser.rules import constants as c

REPO_ROOT = Path(__file__).resolve().parents[1]


def build_payload() -> dict:
    return {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "tokens": {
            "TOKEN_YEAR": c.TOKEN_YEAR,
            "TOKEN_RESOLUTION": c.TOKEN_RESOLUTION,
            "TOKEN_FRAME_RATE": c.TOKEN_FRAME_RATE,
            "TOKEN_SEASON_EP_SEP": c.TOKEN_SEASON_EP_SEP,
            "TOKEN_SOURCE_SEP": c.TOKEN_SOURCE_SEP,
        },
        "patterns": {
            "P_SOURCE": c.P_SOURCE.pattern,
            "P_RES": c.P_RES.pattern,
            "P_VCODEC": c.P_VCODEC.pattern,
            "P_ACODEC": c.P_ACODEC.pattern,
            "P_VHDR": c.P_VHDR.pattern,
            "P_FPS": c.P_FPS.pattern,
            "P_YEAR": c.P_YEAR.pattern,
            "P_SE": c.P_SE.pattern,
            "P_SEP": c.P_SEP.pattern,
            "P_MISC": c.P_MISC.pattern,
            "P_EP_BRACKET": c.P_EP_BRACKET.pattern,
        },
        "lists": {
            "DISC_LAYOUT_DIRS": sorted(c.DISC_LAYOUT_DIRS),
            "GENERIC_SHORT_TITLES": sorted(c.GENERIC_SHORT_TITLES),
        },
    }


def write_js_module(payload: dict, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    content = (
        "// This file is auto-generated by tools/export_parser_constants.py\n"
        "// Do not edit by hand; update Python constants and re-export.\n\n"
        f"export const SHARED_CONSTANTS = {body};\n"
    )
    output_path.write_text(content, encoding="utf-8")


def main() -> None:
    out = REPO_ROOT / "web" / "app" / "src" / "parser" / "constants.generated.js"
    payload = build_payload()
    write_js_module(payload, out)
    print(f"Exported constants -> {out}")


if __name__ == "__main__":
    main()
